title: HopBot
description: Decoding the beers of the Old Continent

url: http://hopbot.eu
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   twitter: hopbot
   facebook: hopbotco
   email: hi@hopbot.eu
   rss: feed.xml
   untappd: hopbot

google_analytics: "UA-42669057-1"

collections:
  podcasts:
    output: true
    permalink: podcast/:title/
