title: HopBot
description: Decoding the beers of the Old Continent

url: http://hopbot.eu
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   twitter: hopbot
   facebook: hopbotco
   email: hi@hopbot.eu

google_analytics: "UA-58263416-1"
